# Generated by Django 3.1.1 on 2020-09-17 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0004_auto_20200917_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(15, 'Grow up kid, then come back when you are 15.')]),
        ),
    ]
