# Generated by Django 3.1.1 on 2020-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0005_auto_20200917_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
